server:
  port: 80
  tomcat:
    uri-encoding: utf-8

spring:
    profiles:
      active: druid
# MyBatis
mybatis:
  #   对应实体类路径
  type-aliases-package: com.anlve.sun.model
  # mapper映射文件扫描
  mapper-locations: classpath:mapper/**/*Mapper.xml

# PageHelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql